(func $or (export "main") (param $x f32) (param $y f32) (param $z f32) (result f32)
  (local $lhs f32)
  (if (result f32)
    (f32.ne (f32.const 0) (local.tee $lhs (local.get $x)))
    (then (local.get $lhs))
    (else
      (if (result f32)
        (f32.ne (f32.const 0) (local.tee $lhs (local.get $y)))
        (then (local.get $lhs))
        (else
          (local.get $z)
        )
      )
    )
  )
)
